#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SUZ")]
public partial class toSQLDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Определения метода расширяемости
  partial void OnCreated();
  partial void InsertSperm_Cities(Sperm_Cities instance);
  partial void UpdateSperm_Cities(Sperm_Cities instance);
  partial void DeleteSperm_Cities(Sperm_Cities instance);
  partial void InsertSperm_Price(Sperm_Price instance);
  partial void UpdateSperm_Price(Sperm_Price instance);
  partial void DeleteSperm_Price(Sperm_Price instance);
  partial void InsertSperm_Zapisi(Sperm_Zapisi instance);
  partial void UpdateSperm_Zapisi(Sperm_Zapisi instance);
  partial void DeleteSperm_Zapisi(Sperm_Zapisi instance);
  partial void InsertUsers(Users instance);
  partial void UpdateUsers(Users instance);
  partial void DeleteUsers(Users instance);
  partial void InsertUzi_Cities(Uzi_Cities instance);
  partial void UpdateUzi_Cities(Uzi_Cities instance);
  partial void DeleteUzi_Cities(Uzi_Cities instance);
  partial void InsertUzi_Doctor(Uzi_Doctor instance);
  partial void UpdateUzi_Doctor(Uzi_Doctor instance);
  partial void DeleteUzi_Doctor(Uzi_Doctor instance);
  partial void InsertUzi_Zapisi(Uzi_Zapisi instance);
  partial void UpdateUzi_Zapisi(Uzi_Zapisi instance);
  partial void DeleteUzi_Zapisi(Uzi_Zapisi instance);
  #endregion
	
	public toSQLDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SUZConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public toSQLDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public toSQLDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public toSQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public toSQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Sperm_Cities> Sperm_Cities
	{
		get
		{
			return this.GetTable<Sperm_Cities>();
		}
	}
	
	public System.Data.Linq.Table<Sperm_Dates> Sperm_Dates
	{
		get
		{
			return this.GetTable<Sperm_Dates>();
		}
	}
	
	public System.Data.Linq.Table<Sperm_Doctor> Sperm_Doctor
	{
		get
		{
			return this.GetTable<Sperm_Doctor>();
		}
	}
	
	public System.Data.Linq.Table<Sperm_Price> Sperm_Price
	{
		get
		{
			return this.GetTable<Sperm_Price>();
		}
	}
	
	public System.Data.Linq.Table<Sperm_Zapisi> Sperm_Zapisi
	{
		get
		{
			return this.GetTable<Sperm_Zapisi>();
		}
	}
	
	public System.Data.Linq.Table<Users> Users
	{
		get
		{
			return this.GetTable<Users>();
		}
	}
	
	public System.Data.Linq.Table<Uzi_Cities> Uzi_Cities
	{
		get
		{
			return this.GetTable<Uzi_Cities>();
		}
	}
	
	public System.Data.Linq.Table<Uzi_Doctor> Uzi_Doctor
	{
		get
		{
			return this.GetTable<Uzi_Doctor>();
		}
	}
	
	public System.Data.Linq.Table<Uzi_Price> Uzi_Price
	{
		get
		{
			return this.GetTable<Uzi_Price>();
		}
	}
	
	public System.Data.Linq.Table<Uzi_Zapisi> Uzi_Zapisi
	{
		get
		{
			return this.GetTable<Uzi_Zapisi>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sperm_Cities")]
public partial class Sperm_Cities : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _City;
	
	private string _MO;
	
	private string _Address;
	
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnMOChanging(string value);
    partial void OnMOChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    #endregion
	
	public Sperm_Cities()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this.OnCityChanging(value);
				this.SendPropertyChanging();
				this._City = value;
				this.SendPropertyChanged("City");
				this.OnCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MO", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string MO
	{
		get
		{
			return this._MO;
		}
		set
		{
			if ((this._MO != value))
			{
				this.OnMOChanging(value);
				this.SendPropertyChanging();
				this._MO = value;
				this.SendPropertyChanged("MO");
				this.OnMOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sperm_Dates")]
public partial class Sperm_Dates
{
	
	private string _date;
	
	private string _city;
	
	private string _mo;
	
	public Sperm_Dates()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string date
	{
		get
		{
			return this._date;
		}
		set
		{
			if ((this._date != value))
			{
				this._date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this._city = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string mo
	{
		get
		{
			return this._mo;
		}
		set
		{
			if ((this._mo != value))
			{
				this._mo = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sperm_Doctor")]
public partial class Sperm_Doctor
{
	
	private int _id;
	
	private string _name;
	
	private string _city;
	
	private string _mo;
	
	public Sperm_Doctor()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this._name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this._city = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string mo
	{
		get
		{
			return this._mo;
		}
		set
		{
			if ((this._mo != value))
			{
				this._mo = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sperm_Price")]
public partial class Sperm_Price : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Test_code;
	
	private string _Test_city;
	
	private string _Test_mo;
	
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTest_codeChanging(string value);
    partial void OnTest_codeChanged();
    partial void OnTest_cityChanging(string value);
    partial void OnTest_cityChanged();
    partial void OnTest_moChanging(string value);
    partial void OnTest_moChanged();
    #endregion
	
	public Sperm_Price()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Test_code", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Test_code
	{
		get
		{
			return this._Test_code;
		}
		set
		{
			if ((this._Test_code != value))
			{
				this.OnTest_codeChanging(value);
				this.SendPropertyChanging();
				this._Test_code = value;
				this.SendPropertyChanged("Test_code");
				this.OnTest_codeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Test_city", DbType="NVarChar(MAX)")]
	public string Test_city
	{
		get
		{
			return this._Test_city;
		}
		set
		{
			if ((this._Test_city != value))
			{
				this.OnTest_cityChanging(value);
				this.SendPropertyChanging();
				this._Test_city = value;
				this.SendPropertyChanged("Test_city");
				this.OnTest_cityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Test_mo", DbType="NVarChar(MAX)")]
	public string Test_mo
	{
		get
		{
			return this._Test_mo;
		}
		set
		{
			if ((this._Test_mo != value))
			{
				this.OnTest_moChanging(value);
				this.SendPropertyChanging();
				this._Test_mo = value;
				this.SendPropertyChanged("Test_mo");
				this.OnTest_moChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sperm_Zapisi")]
public partial class Sperm_Zapisi : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _name_1;
	
	private string _name_2;
	
	private string _name_3;
	
	private string _date;
	
	private string _time;
	
	private string _doctor;
	
	private string _phone;
	
	private bool _call;
	
	private bool _visit;
	
	private string _administrator;
	
	private string _usluga;
	
	private string _city;
	
	private string _mo;
	
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onname_1Changing(string value);
    partial void Onname_1Changed();
    partial void Onname_2Changing(string value);
    partial void Onname_2Changed();
    partial void Onname_3Changing(string value);
    partial void Onname_3Changed();
    partial void OndateChanging(string value);
    partial void OndateChanged();
    partial void OntimeChanging(string value);
    partial void OntimeChanged();
    partial void OndoctorChanging(string value);
    partial void OndoctorChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OncallChanging(bool value);
    partial void OncallChanged();
    partial void OnvisitChanging(bool value);
    partial void OnvisitChanged();
    partial void OnadministratorChanging(string value);
    partial void OnadministratorChanged();
    partial void OnuslugaChanging(string value);
    partial void OnuslugaChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnmoChanging(string value);
    partial void OnmoChanged();
    #endregion
	
	public Sperm_Zapisi()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_1", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string name_1
	{
		get
		{
			return this._name_1;
		}
		set
		{
			if ((this._name_1 != value))
			{
				this.Onname_1Changing(value);
				this.SendPropertyChanging();
				this._name_1 = value;
				this.SendPropertyChanged("name_1");
				this.Onname_1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_2", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string name_2
	{
		get
		{
			return this._name_2;
		}
		set
		{
			if ((this._name_2 != value))
			{
				this.Onname_2Changing(value);
				this.SendPropertyChanging();
				this._name_2 = value;
				this.SendPropertyChanged("name_2");
				this.Onname_2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_3", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string name_3
	{
		get
		{
			return this._name_3;
		}
		set
		{
			if ((this._name_3 != value))
			{
				this.Onname_3Changing(value);
				this.SendPropertyChanging();
				this._name_3 = value;
				this.SendPropertyChanged("name_3");
				this.Onname_3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string date
	{
		get
		{
			return this._date;
		}
		set
		{
			if ((this._date != value))
			{
				this.OndateChanging(value);
				this.SendPropertyChanging();
				this._date = value;
				this.SendPropertyChanged("date");
				this.OndateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string time
	{
		get
		{
			return this._time;
		}
		set
		{
			if ((this._time != value))
			{
				this.OntimeChanging(value);
				this.SendPropertyChanging();
				this._time = value;
				this.SendPropertyChanged("time");
				this.OntimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doctor", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string doctor
	{
		get
		{
			return this._doctor;
		}
		set
		{
			if ((this._doctor != value))
			{
				this.OndoctorChanging(value);
				this.SendPropertyChanging();
				this._doctor = value;
				this.SendPropertyChanged("doctor");
				this.OndoctorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string phone
	{
		get
		{
			return this._phone;
		}
		set
		{
			if ((this._phone != value))
			{
				this.OnphoneChanging(value);
				this.SendPropertyChanging();
				this._phone = value;
				this.SendPropertyChanged("phone");
				this.OnphoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_call", DbType="Bit NOT NULL")]
	public bool call
	{
		get
		{
			return this._call;
		}
		set
		{
			if ((this._call != value))
			{
				this.OncallChanging(value);
				this.SendPropertyChanging();
				this._call = value;
				this.SendPropertyChanged("call");
				this.OncallChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit", DbType="Bit NOT NULL")]
	public bool visit
	{
		get
		{
			return this._visit;
		}
		set
		{
			if ((this._visit != value))
			{
				this.OnvisitChanging(value);
				this.SendPropertyChanging();
				this._visit = value;
				this.SendPropertyChanged("visit");
				this.OnvisitChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_administrator", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string administrator
	{
		get
		{
			return this._administrator;
		}
		set
		{
			if ((this._administrator != value))
			{
				this.OnadministratorChanging(value);
				this.SendPropertyChanging();
				this._administrator = value;
				this.SendPropertyChanged("administrator");
				this.OnadministratorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usluga", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string usluga
	{
		get
		{
			return this._usluga;
		}
		set
		{
			if ((this._usluga != value))
			{
				this.OnuslugaChanging(value);
				this.SendPropertyChanging();
				this._usluga = value;
				this.SendPropertyChanged("usluga");
				this.OnuslugaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this.OncityChanging(value);
				this.SendPropertyChanging();
				this._city = value;
				this.SendPropertyChanged("city");
				this.OncityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string mo
	{
		get
		{
			return this._mo;
		}
		set
		{
			if ((this._mo != value))
			{
				this.OnmoChanging(value);
				this.SendPropertyChanging();
				this._mo = value;
				this.SendPropertyChanged("mo");
				this.OnmoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
public partial class Users : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Login;
	
	private string _Password;
	
	private string _Rights;
	
	private string _Username;
	
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLoginChanging(string value);
    partial void OnLoginChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnRightsChanging(string value);
    partial void OnRightsChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    #endregion
	
	public Users()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Login
	{
		get
		{
			return this._Login;
		}
		set
		{
			if ((this._Login != value))
			{
				this.OnLoginChanging(value);
				this.SendPropertyChanging();
				this._Login = value;
				this.SendPropertyChanged("Login");
				this.OnLoginChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rights", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Rights
	{
		get
		{
			return this._Rights;
		}
		set
		{
			if ((this._Rights != value))
			{
				this.OnRightsChanging(value);
				this.SendPropertyChanging();
				this._Rights = value;
				this.SendPropertyChanged("Rights");
				this.OnRightsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(MAX)")]
	public string Username
	{
		get
		{
			return this._Username;
		}
		set
		{
			if ((this._Username != value))
			{
				this.OnUsernameChanging(value);
				this.SendPropertyChanging();
				this._Username = value;
				this.SendPropertyChanged("Username");
				this.OnUsernameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Uzi_Cities")]
public partial class Uzi_Cities : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _mo;
	
	private string _city;
	
	private string _duration;
	
	private string _address;
	
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmoChanging(string value);
    partial void OnmoChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OndurationChanging(string value);
    partial void OndurationChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    #endregion
	
	public Uzi_Cities()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo", DbType="NVarChar(MAX)")]
	public string mo
	{
		get
		{
			return this._mo;
		}
		set
		{
			if ((this._mo != value))
			{
				this.OnmoChanging(value);
				this.SendPropertyChanging();
				this._mo = value;
				this.SendPropertyChanged("mo");
				this.OnmoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(MAX)")]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this.OncityChanging(value);
				this.SendPropertyChanging();
				this._city = value;
				this.SendPropertyChanged("city");
				this.OncityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duration", DbType="NVarChar(MAX)")]
	public string duration
	{
		get
		{
			return this._duration;
		}
		set
		{
			if ((this._duration != value))
			{
				this.OndurationChanging(value);
				this.SendPropertyChanging();
				this._duration = value;
				this.SendPropertyChanged("duration");
				this.OndurationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(MAX)")]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this.OnaddressChanging(value);
				this.SendPropertyChanging();
				this._address = value;
				this.SendPropertyChanged("address");
				this.OnaddressChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Uzi_Doctor")]
public partial class Uzi_Doctor : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _DOCTOR;
	
	private string _CITY;
	
	private string _MO;
	
	private string _RESTRICTION;
	
	private string _TEST;
	
	private string _TEST_OMS;
	
	private string _DURATION;
	
	private string _DURATION_OMS;
	
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDOCTORChanging(string value);
    partial void OnDOCTORChanged();
    partial void OnCITYChanging(string value);
    partial void OnCITYChanged();
    partial void OnMOChanging(string value);
    partial void OnMOChanged();
    partial void OnRESTRICTIONChanging(string value);
    partial void OnRESTRICTIONChanged();
    partial void OnTESTChanging(string value);
    partial void OnTESTChanged();
    partial void OnTEST_OMSChanging(string value);
    partial void OnTEST_OMSChanged();
    partial void OnDURATIONChanging(string value);
    partial void OnDURATIONChanged();
    partial void OnDURATION_OMSChanging(string value);
    partial void OnDURATION_OMSChanged();
    #endregion
	
	public Uzi_Doctor()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCTOR", DbType="NVarChar(MAX)")]
	public string DOCTOR
	{
		get
		{
			return this._DOCTOR;
		}
		set
		{
			if ((this._DOCTOR != value))
			{
				this.OnDOCTORChanging(value);
				this.SendPropertyChanging();
				this._DOCTOR = value;
				this.SendPropertyChanged("DOCTOR");
				this.OnDOCTORChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="NVarChar(MAX)")]
	public string CITY
	{
		get
		{
			return this._CITY;
		}
		set
		{
			if ((this._CITY != value))
			{
				this.OnCITYChanging(value);
				this.SendPropertyChanging();
				this._CITY = value;
				this.SendPropertyChanged("CITY");
				this.OnCITYChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MO", DbType="NVarChar(MAX)")]
	public string MO
	{
		get
		{
			return this._MO;
		}
		set
		{
			if ((this._MO != value))
			{
				this.OnMOChanging(value);
				this.SendPropertyChanging();
				this._MO = value;
				this.SendPropertyChanged("MO");
				this.OnMOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESTRICTION", DbType="NVarChar(MAX)")]
	public string RESTRICTION
	{
		get
		{
			return this._RESTRICTION;
		}
		set
		{
			if ((this._RESTRICTION != value))
			{
				this.OnRESTRICTIONChanging(value);
				this.SendPropertyChanging();
				this._RESTRICTION = value;
				this.SendPropertyChanged("RESTRICTION");
				this.OnRESTRICTIONChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEST", DbType="NVarChar(MAX)")]
	public string TEST
	{
		get
		{
			return this._TEST;
		}
		set
		{
			if ((this._TEST != value))
			{
				this.OnTESTChanging(value);
				this.SendPropertyChanging();
				this._TEST = value;
				this.SendPropertyChanged("TEST");
				this.OnTESTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEST_OMS", DbType="NVarChar(MAX)")]
	public string TEST_OMS
	{
		get
		{
			return this._TEST_OMS;
		}
		set
		{
			if ((this._TEST_OMS != value))
			{
				this.OnTEST_OMSChanging(value);
				this.SendPropertyChanging();
				this._TEST_OMS = value;
				this.SendPropertyChanged("TEST_OMS");
				this.OnTEST_OMSChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DURATION", DbType="NVarChar(MAX)")]
	public string DURATION
	{
		get
		{
			return this._DURATION;
		}
		set
		{
			if ((this._DURATION != value))
			{
				this.OnDURATIONChanging(value);
				this.SendPropertyChanging();
				this._DURATION = value;
				this.SendPropertyChanged("DURATION");
				this.OnDURATIONChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DURATION_OMS", DbType="NVarChar(MAX)")]
	public string DURATION_OMS
	{
		get
		{
			return this._DURATION_OMS;
		}
		set
		{
			if ((this._DURATION_OMS != value))
			{
				this.OnDURATION_OMSChanging(value);
				this.SendPropertyChanging();
				this._DURATION_OMS = value;
				this.SendPropertyChanged("DURATION_OMS");
				this.OnDURATION_OMSChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Uzi_Price")]
public partial class Uzi_Price
{
	
	private int _id;
	
	private string _test;
	
	private string _description;
	
	private string _nsk_price;
	
	private string _krs_price;
	
	private string _tomsk_price;
	
	private string _omsk_price;
	
	private string _irk_price;
	
	private string _common_prep;
	
	private string _tomsk_prep;
	
	public Uzi_Price()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_test", DbType="NVarChar(MAX)")]
	public string test
	{
		get
		{
			return this._test;
		}
		set
		{
			if ((this._test != value))
			{
				this._test = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(MAX)")]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this._description = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nsk_price", DbType="NVarChar(MAX)")]
	public string nsk_price
	{
		get
		{
			return this._nsk_price;
		}
		set
		{
			if ((this._nsk_price != value))
			{
				this._nsk_price = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_krs_price", DbType="NVarChar(MAX)")]
	public string krs_price
	{
		get
		{
			return this._krs_price;
		}
		set
		{
			if ((this._krs_price != value))
			{
				this._krs_price = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tomsk_price", DbType="NVarChar(MAX)")]
	public string tomsk_price
	{
		get
		{
			return this._tomsk_price;
		}
		set
		{
			if ((this._tomsk_price != value))
			{
				this._tomsk_price = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_omsk_price", DbType="NVarChar(MAX)")]
	public string omsk_price
	{
		get
		{
			return this._omsk_price;
		}
		set
		{
			if ((this._omsk_price != value))
			{
				this._omsk_price = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_irk_price", DbType="NVarChar(MAX)")]
	public string irk_price
	{
		get
		{
			return this._irk_price;
		}
		set
		{
			if ((this._irk_price != value))
			{
				this._irk_price = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_common_prep", DbType="NVarChar(MAX)")]
	public string common_prep
	{
		get
		{
			return this._common_prep;
		}
		set
		{
			if ((this._common_prep != value))
			{
				this._common_prep = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tomsk_prep", DbType="NVarChar(MAX)")]
	public string tomsk_prep
	{
		get
		{
			return this._tomsk_prep;
		}
		set
		{
			if ((this._tomsk_prep != value))
			{
				this._tomsk_prep = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Uzi_Zapisi")]
public partial class Uzi_Zapisi : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _date;
	
	private string _time;
	
	private string _age;
	
	private string _sex;
	
	private string _phone;
	
	private string _city;
	
	private string _mo;
	
	private string _doctor;
	
	private string _services;
	
	private string _admin;
	
	private System.Nullable<bool> _accept;
	
	private string _comment;
	
	private string _name_1;
	
	private string _name_2;
	
	private string _name_3;
	
	private System.Nullable<bool> _hidden;
	
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OndateChanging(string value);
    partial void OndateChanged();
    partial void OntimeChanging(string value);
    partial void OntimeChanged();
    partial void OnageChanging(string value);
    partial void OnageChanged();
    partial void OnsexChanging(string value);
    partial void OnsexChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnmoChanging(string value);
    partial void OnmoChanged();
    partial void OndoctorChanging(string value);
    partial void OndoctorChanged();
    partial void OnservicesChanging(string value);
    partial void OnservicesChanged();
    partial void OnadminChanging(string value);
    partial void OnadminChanged();
    partial void OnacceptChanging(System.Nullable<bool> value);
    partial void OnacceptChanged();
    partial void OncommentChanging(string value);
    partial void OncommentChanged();
    partial void Onname_1Changing(string value);
    partial void Onname_1Changed();
    partial void Onname_2Changing(string value);
    partial void Onname_2Changed();
    partial void Onname_3Changing(string value);
    partial void Onname_3Changed();
    partial void OnhiddenChanging(System.Nullable<bool> value);
    partial void OnhiddenChanged();
    #endregion
	
	public Uzi_Zapisi()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="NVarChar(MAX)")]
	public string date
	{
		get
		{
			return this._date;
		}
		set
		{
			if ((this._date != value))
			{
				this.OndateChanging(value);
				this.SendPropertyChanging();
				this._date = value;
				this.SendPropertyChanged("date");
				this.OndateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="NVarChar(MAX)")]
	public string time
	{
		get
		{
			return this._time;
		}
		set
		{
			if ((this._time != value))
			{
				this.OntimeChanging(value);
				this.SendPropertyChanging();
				this._time = value;
				this.SendPropertyChanged("time");
				this.OntimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="NVarChar(MAX)")]
	public string age
	{
		get
		{
			return this._age;
		}
		set
		{
			if ((this._age != value))
			{
				this.OnageChanging(value);
				this.SendPropertyChanging();
				this._age = value;
				this.SendPropertyChanged("age");
				this.OnageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="NVarChar(MAX)")]
	public string sex
	{
		get
		{
			return this._sex;
		}
		set
		{
			if ((this._sex != value))
			{
				this.OnsexChanging(value);
				this.SendPropertyChanging();
				this._sex = value;
				this.SendPropertyChanged("sex");
				this.OnsexChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(MAX)")]
	public string phone
	{
		get
		{
			return this._phone;
		}
		set
		{
			if ((this._phone != value))
			{
				this.OnphoneChanging(value);
				this.SendPropertyChanging();
				this._phone = value;
				this.SendPropertyChanged("phone");
				this.OnphoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(MAX)")]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this.OncityChanging(value);
				this.SendPropertyChanging();
				this._city = value;
				this.SendPropertyChanged("city");
				this.OncityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo", DbType="NVarChar(MAX)")]
	public string mo
	{
		get
		{
			return this._mo;
		}
		set
		{
			if ((this._mo != value))
			{
				this.OnmoChanging(value);
				this.SendPropertyChanging();
				this._mo = value;
				this.SendPropertyChanged("mo");
				this.OnmoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doctor", DbType="NVarChar(MAX)")]
	public string doctor
	{
		get
		{
			return this._doctor;
		}
		set
		{
			if ((this._doctor != value))
			{
				this.OndoctorChanging(value);
				this.SendPropertyChanging();
				this._doctor = value;
				this.SendPropertyChanged("doctor");
				this.OndoctorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_services", DbType="NVarChar(MAX)")]
	public string services
	{
		get
		{
			return this._services;
		}
		set
		{
			if ((this._services != value))
			{
				this.OnservicesChanging(value);
				this.SendPropertyChanging();
				this._services = value;
				this.SendPropertyChanged("services");
				this.OnservicesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin", DbType="NVarChar(MAX)")]
	public string admin
	{
		get
		{
			return this._admin;
		}
		set
		{
			if ((this._admin != value))
			{
				this.OnadminChanging(value);
				this.SendPropertyChanging();
				this._admin = value;
				this.SendPropertyChanged("admin");
				this.OnadminChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accept", DbType="Bit")]
	public System.Nullable<bool> accept
	{
		get
		{
			return this._accept;
		}
		set
		{
			if ((this._accept != value))
			{
				this.OnacceptChanging(value);
				this.SendPropertyChanging();
				this._accept = value;
				this.SendPropertyChanged("accept");
				this.OnacceptChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="NVarChar(MAX)")]
	public string comment
	{
		get
		{
			return this._comment;
		}
		set
		{
			if ((this._comment != value))
			{
				this.OncommentChanging(value);
				this.SendPropertyChanging();
				this._comment = value;
				this.SendPropertyChanged("comment");
				this.OncommentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_1", DbType="NVarChar(MAX)")]
	public string name_1
	{
		get
		{
			return this._name_1;
		}
		set
		{
			if ((this._name_1 != value))
			{
				this.Onname_1Changing(value);
				this.SendPropertyChanging();
				this._name_1 = value;
				this.SendPropertyChanged("name_1");
				this.Onname_1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_2", DbType="NVarChar(MAX)")]
	public string name_2
	{
		get
		{
			return this._name_2;
		}
		set
		{
			if ((this._name_2 != value))
			{
				this.Onname_2Changing(value);
				this.SendPropertyChanging();
				this._name_2 = value;
				this.SendPropertyChanged("name_2");
				this.Onname_2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_3", DbType="NVarChar(MAX)")]
	public string name_3
	{
		get
		{
			return this._name_3;
		}
		set
		{
			if ((this._name_3 != value))
			{
				this.Onname_3Changing(value);
				this.SendPropertyChanging();
				this._name_3 = value;
				this.SendPropertyChanged("name_3");
				this.Onname_3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hidden", DbType="Bit")]
	public System.Nullable<bool> hidden
	{
		get
		{
			return this._hidden;
		}
		set
		{
			if ((this._hidden != value))
			{
				this.OnhiddenChanging(value);
				this.SendPropertyChanging();
				this._hidden = value;
				this.SendPropertyChanged("hidden");
				this.OnhiddenChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
